{*
 generated by Prestaweb.ru from pwdeveloper module
*}

<div class="pwmultishopswitcher">
    <div class="shop-selection">
        <span class="shop-select">Выберите город:</span>
        {if $shops}
        <select name="shop-select" id="shop-select" title="shop-select">
            {foreach from=$shops key=k item=v}
                <option value="{$smarty.server.REQUEST_SCHEME}://{$v.domain}" {if $smarty.server.SERVER_NAME == $v.domain}selected="selected"{/if}>{$v.name}</option>
            {/foreach}
        </select>
        {/if}
    </div>
</div>